server:
  port: 0 # Using port 0 tells Spring Boot to assign a random available port.

spring:
  application:
    name: auth-service # This name will be used to register with Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db # Replace with your DB details
    username: your_postgres_user
    password: your_postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the schema. Use "validate" in production.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Prefer using IP address for registration
    prefer-ip-address: true

# Custom properties for our JWT implementation
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 hours
      refresh-token:
        expiration: 604800000 # 7 days
