server:
  port: 8080 # The single public-facing port for the entire backend

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for the advanced Auth Service
        - id: auth-service
          uri: lb://auth-service # "lb://" tells the gateway to look up the service in Eureka
          predicates:
            - Path=/api/v1/auth/**

        # Route for the advanced Business Name Generator Service
        - id: business-name-generator
          uri: lb://business-name-generator
          predicates:
            - Path=/api/v1/business-generation/**

        # Route for the advanced RAG Service
        - id: rag-service
          uri: lb://rag-service
          predicates:
            - Path=/api/v1/rag/**

        # Route for the advanced Chat Service
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/chat/**

        # Route for the advanced Logo Generator Service
        - id: logo-generator
          uri: lb://logo-generator
          predicates:
            - Path=/api/v1/logo/**

        # Route for the advanced Docs Generator Service
        - id: docs-generator
          uri: lb://docs-generator
          predicates:
            - Path=/api/v1/document-generation/**

        # Route for the advanced Presentation Generator Service
        - id: presentation-generator
          uri: lb://presentation-generator
          predicates:
            - Path=/api/v1/presentation/**

        # Route for the advanced Short Video Generator Service
        - id: short-video-generator
          uri: lb://short-video-generator
          predicates:
            - Path=/api/v1/short-video/**

        # Route for the advanced Website Builder Service
        - id: website-builder
          uri: lb://website-builder
          predicates:
            - Path=/api/v1/website-builder/**
        
        # Route for the advanced Market Analysis Service
        - id: market-analysis-service
          uri: lb://market-analysis-service
          predicates:
            - Path=/api/v1/market-analysis/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The address of our "phonebook"
  instance:
    prefer-ip-address: true

