server:
  port: 0

spring:
  application:
    name: rag-service
  # Database Configuration for rag_db
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: your_postgres_user # CHANGE ME
    password: your_postgres_password # CHANGE ME
    driver-class-name: org.postgresql.Driver
  # Spring AI Configuration
  ai:
    # Google Gemini for Chat and Embeddings
    google:
      gemini:
        api-key: "YOUR_GEMINI_API_KEY" # CHANGE ME
        chat:
          options:
            model: gemini-1.5-flash-latest
            temperature: 0.4
        embedding:
          options:
            model: text-embedding-004 # Google's 768-dimension embedding model
    # Vector Store Configuration
    vector:
      store:
        pgvector:
          index-type: HNSW # Use the high-performance HNSW index
          distance-type: COSINE # Cosine distance is good for semantic similarity
          # The dimension must match the embedding model's output
          dimensions: 768

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

