server:
  port: 0

spring:
  application:
    name: chat-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Placeholder for the generative AI model API
llm:
  api:
    url: "https://api.generative-ai-provider.com/v1/chat/completions"
