server:
  port: 0 # Run on a random available port

spring:
  application:
    name: business-name-generator
  # Database Configuration for business_db
  datasource:
    url: jdbc:postgresql://localhost:5432/business_db
    username: your_postgres_user # CHANGE ME
    password: your_postgres_password # CHANGE ME
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Best practice for production; schema managed via scripts
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Spring AI Configuration for OpenAI
  ai:
    openai:
      api-key: "sk-..." # CHANGE ME - Your OpenAI API Key
      chat:
        options:
          model: gpt-3.5-turbo # A cost-effective model for name generation
          temperature: 0.8 # Higher temperature for more creative names

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

